[package]
name = "measurement"
version = "0.1.0"
authors = ["noirgif <nomaru@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
